#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot picom or compton if it exists
picom --backend glx &> /dev/null & 

#set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.ron" > $XDG_RUNTIME_DIR/leftwm/commands.pipe
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"


echo "$SCRIPTPATH" > ~/test.txt
#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.jpg
fi

xset b 100 0 0
xset r rate 400 35

# xmodmap -e "add Control = Control_L"
setxkbmap -option caps:escape
setxkbmap -option altwin:swap_lalt_lwin
xmodmap -e "keycode 9 = grave asciitilde"
xmodmap -e "keycode 64 = keycode 133"
xmodmap -e "keycode 133 = keycode 64"

/home/avgt/.local/bin/sven unlock &> /dev/null &

pactl set-card-profile alsa_card.pci-0000_00_1f.3 output:analog-stereo+input:analog-stereo
nm-applet &

xinput set-prop 10 "libinput Tapping Enabled" 1
xinput set-prop 10 "libinput Natural Scrolling Enabled" 1
xinput set-prop "Logitech G502 HERO Gaming Mouse" "libinput Natural Scrolling Enabled" 0 &
# Hide cursor while typing
unclutter &> /dev/null &

sleep 3

index=0
monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do 
  barname="mainbar$index"
  monitor=$monitor offsetx=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=index+1
done

revert
# nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1 > /dev/null
# nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1 > /dev/null
