-- lua/daze/config/lsp-zero.lua
local lsp = require("lsp-zero")
local cmp = require("cmp")

-- tsserver config
-- lsp.configure("tsserver", {
-- 	filetypes = { "javascript", "typescript", "javascriptreact", "typescriptreact", "vue" },
-- 	on_attach = function(client, bufnr)
-- 		-- Disable tsserver formatting if using prettier
-- 		-- client.server_capabilities.documentFormattingProvider = false
-- 	end,
-- })
--
-- -- eslint config: only fix-on-save, no formatting/definitions
-- lsp.configure("eslint", {
-- 	on_attach = function(client, bufnr)
-- 		client.server_capabilities.hoverProvider = false
-- 		client.server_capabilities.definitionProvider = false
-- 		client.server_capabilities.renameProvider = false
-- 		vim.api.nvim_create_autocmd("BufWritePre", {
-- 			buffer = bufnr,
-- 			command = "EslintFixAll",
-- 		})
-- 	end,
-- })

--
-- -- ===============================
-- -- LSP ZERO PRESET
-- -- ===============================
-- lsp.preset("recommended")
--
-- -- Ensure these servers are installed (lsp-zero manages them)
-- lsp.ensure_installed({
--
-- 	"dartls",
-- 	"intelephense",
-- 	"tsserver",
-- 	"jsonls",
-- 	"eslint",
-- })
--
-- -- ===============================
-- -- nvim-cmp Setup
-- -- ===============================
-- cmp.setup({
-- 	preselect = cmp.PreselectMode.None,
-- 	completion = { completeopt = "menu,menuone,noinsert,noselect" },
-- })
--
-- -- ===============================
-- -- DART
-- -- ===============================
-- lsp.configure("dartls", {
-- 	cmd = { "dart", "language-server", "--protocol=lsp" },
-- 	filetypes = { "dart" },
-- 	root_dir = require("lspconfig.util").root_pattern("pubspec.yaml", ".git"),
-- })
--
-- -- ===============================
-- -- PHP (Intelephense)
-- -- ===============================
-- lsp.configure("intelephense", {
-- 	cmd = { "intelephense", "--stdio" },
-- 	filetypes = { "php" },
-- 	root_dir = require("lspconfig.util").root_pattern("composer.json", ".git", ".autocomplete"),
-- 	on_attach = function(client, bufnr)
-- 		client.server_capabilities.documentFormattingProvider = false
-- 	end,
-- })
--
-- -- ===============================
-- -- JSON
-- -- ===============================
-- lsp.configure("jsonls", {})
--
-- -- ===============================
-- -- TypeScript / JavaScript
-- -- ===============================
-- lsp.configure("tsserver", {
-- 	cmd = { "typescript-language-server", "--stdio" },
-- 	filetypes = { "javascript", "typescript", "javascriptreact", "typescriptreact", "vue" },
-- 	root_dir = require("lspconfig.util").root_pattern("package.json", "tsconfig.json", ".git"),
-- 	on_attach = function(client, bufnr)
-- 		-- Disable formatting if using Prettier
-- 		client.server_capabilities.documentFormattingProvider = false
--
-- 		-- Keymaps
-- 		vim.keymap.set("n", "gd", vim.lsp.buf.definition, { buffer = bufnr, noremap = true, silent = true })
-- 		vim.keymap.set("n", "K", vim.lsp.buf.hover, { buffer = bufnr, noremap = true, silent = true })
-- 	end,
-- })
--
-- -- Optional: Filter TS diagnostics (like you had before)
-- lsp.configure("tsserver", {
-- 	handlers = {
-- 		["textDocument/publishDiagnostics"] = function(_, result, ctx, config)
-- 			if not result.diagnostics then
-- 				return
-- 			end
-- 			local idx = 1
-- 			while idx <= #result.diagnostics do
-- 				local entry = result.diagnostics[idx]
-- 				local formatter = require("format-ts-errors")[entry.code]
-- 				entry.message = formatter and formatter(entry.message) or entry.message
-- 				if entry.code == 80001 then
-- 					table.remove(result.diagnostics, idx)
-- 				else
-- 					idx = idx + 1
-- 				end
-- 			end
-- 			vim.lsp.diagnostic.on_publish_diagnostics(_, result, ctx, config)
-- 		end,
-- 	},
-- })
--
-- -- ===============================
-- -- ESLint
-- -- ===============================
-- lsp.configure("eslint", {
-- 	on_attach = function(client, bufnr)
-- vim.api.nvim_create_autocmd("BufWritePre", {
-- 	buffer = bufnr,
-- 	command = "EslintFixAll",
-- })
-- 	end,
-- })
--
-- -- ===============================
-- -- FINALIZE LSP-SETUP
-- -- ===============================
-- lsp.setup()
--
-- -- Optional inlay hints (Neovim 0.10+)
-- lsp.inlay_hint(0, true)
--
-- -- Custom cmp config
require("daze.config.cmp")
