#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity         1.0
yabai -m config normal_window_opacity         0.90
yabai -m config insert_feedback_color         0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action           swap

# layout
yabai -m config layout                       bsp

# padding
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                2
yabai -m config right_padding               2
yabai -m config window_gap                   2

# space labels
#
# # app rules - space assignments
# yabai -m rule --add app="^Alacritty$"           space=1
# yabai -m rule --add app="^Firefox Developer Edition$" space=2
# yabai -m rule --add app="^Spotify$"             space=3
# yabai -m rule --add app="^Slack$"               space=4
# yabai -m rule --add app="^Discord$"             space=4
# yabai -m rule --add app="^Telegram$"            space=4

echo "yabai configuration loaded.."
